apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beszel-credentials
  namespace: default
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: beszel-key
      remoteRef:
        key: beszel/username
    - secretKey: beszel-token
      remoteRef:
        key: beszel/password
    - secretKey: beszel-hub-url
      remoteRef:
        key: beszel/hub-url
