apiVersion: external-secrets.io/v1
kind: ExternalSecret
# tailscale-operator looks for a secret of this name by default
# https://github.com/tailscale/tailscale/blob/ae95d8d22231a6e24e11bf44eadaf48b9a62aa3d/cmd/k8s-operator/deploy/chart/values.yaml#L4-L6
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: client_id
      remoteRef:
        key: tailscale-operator/username
    - secretKey: client_secret
      remoteRef:
        key: tailscale-operator/credential
