---
services:
  owncloud:
    image: owncloud/server:10.16.0@sha256:b603cbc572b3a82b675c3c401c54e48390fa026f16b917e87eee8c98b41659c9
    container_name: owncloud
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - owncloud-backend
    environment:
      - OWNCLOUD_DOMAIN=owncloud.local.elmurphy.com
      - OWNCLOUD_TRUSTED_DOMAINS=owncloud.local.elmurphy.com
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=${OWNCLOUD_DB_PASSWORD}
      - OWNCLOUD_DB_HOST=owncloud-mariadb
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=owncloud-redis
    volumes:
      - owncloud-data:/mnt/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.owncloud.rule=Host(`owncloud.local.elmurphy.com`)
      - traefik.http.routers.owncloud.tls=true
      - traefik.http.services.owncloud.loadbalancer.server.port=8080
    depends_on:
      - owncloud-mariadb
      - owncloud-redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  owncloud-mariadb:
    image: mariadb:12.2.2@sha256:b1cb255a9939d28a1856815f0de6046c20c28c21b92a9f2696bc782b247a47ee # minimum required ownCloud version is 10.9
    container_name: owncloud-mariadb
    security_opt:
      - no-new-privileges:true
    networks:
      - owncloud-backend
    environment:
      - MYSQL_ROOT_PASSWORD=${OWNCLOUD_DB_PASSWORD}
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=${OWNCLOUD_DB_PASSWORD}
      - MYSQL_DATABASE=owncloud
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - owncloud-db:/var/lib/mysql
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  owncloud-redis:
    image: redis:8@sha256:7b6fb55d8b0adcd77269dc52b3cfffe5f59ca5d43dec3c90dbe18aacce7942e1
    container_name: owncloud-redis
    security_opt:
      - no-new-privileges:true
    networks:
      - owncloud-backend
    volumes:
      - owncloud-cache:/data
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  owncloud-data:
    name: owncloud-data
  owncloud-db:
    name: owncloud-db
  owncloud-cache:
    name: owncloud-cache

networks:
  proxy:
    external: true
  owncloud-backend:
    name: owncloud-backend
    internal: true
    ipam:
      config:
        - subnet: 172.40.1.0/24
