---
services:
  komga:
    image: gotson/komga:1.23.6@sha256:09129eae6eff50337f039bd6e99d995126cb03226950c80e9864cbc05f10a661
    container_name: komga
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - komga-data:/config:rw
      - /mnt/data/media/manga:/data:rw
      - /etc/timezone:/etc/timezone:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.komga.rule=Host(`komga.local.elmurphy.com`)
      - traefik.http.routers.komga.tls=true
      - traefik.http.services.komga.loadbalancer.server.port=25600
    restart: unless-stopped

volumes:
  komga-data:
    name: komga-data

networks:
  proxy:
    external: true
